host: libbladeRF: fix compile error on empty struct
clang on OS X complains thus:

error: empty struct has size 0 in C, size 1 in C++ [-Werror,-Wextern-c-compat]