host: bladeRF-cli: fix uninitialized status var in cmd_poke
Fixes clang warning:

poke.c:137:24: error: variable 'status' is used uninitialized whenever
'if' condition is false [-Werror ,-Wsometimes-uninitialized]

Realistically, there is no way that 'status' could be used on line 141
without one of f, f2, or f3 being true (thus setting the value), due to
the test on 132. There is no harm in initializing it anyway, though.